name: Reusable Playwright

on:
  workflow_call:
    inputs:
        command:
          required: true
          type: string
        browser:
          required: true
          type: string
        engine:
          required: true
          type: string
        suite:
          type: string
        runner:
          type: string
    secrets:
        SLACK_WEBHOOK_URL:
          required: true

jobs:
  execute-playwright:
    name: Execute Playwright
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 30

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Playwright environment
        uses: ./.github/actions/setup-playwright.yml
        with:
          browser: ${{ inputs.engine }}
          node-version: "24"

      - name: Run Playwright tests
        run: yarn ${{ inputs.command }} --project="${{  inputs.browser }}"

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.suite }}-${{ inputs.browser }}-report
          path: playwright-report
          retention-days: 7

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              ${{ job.status == 'success' && '✅' || '❌' }} Playwright test: ${{ job.status }}
              Repository: ${{ github.repository }}
              Branch: ${{ github.ref_name }}
              Test suite: ${{ inputs.command }}
              Browser: ${{ inputs.browser }}
              Triggered by: ${{ github.actor }}
              Run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}